### ISSUE TITLE
是否考虑使用C++11来代替部分基础库实现？

### ISSUE THREAD

**Issue by wumuzi520** [brpc/brpc#42]
如果使用C11的话，应该能去掉不少代码，看起来也会清爽一些啊

**Comment by jamesge** [comment]
你指的是C++11吧，这个会逐渐改的，为了语法拉分支是不值得的

**Comment by czfgege** [comment]
c information is not complete, how much money behind the equity pledge, and Jia Yue Ting on the pledge of the number of additional assurance, Tencent technology temporarily unable to know. But according to the three institutions pledged the amount of equity, that is 1.077 billion yuan, the final loan amount set at several billion level or more. A need to be avoided panic If there are more institutions to follow up the rush, music is likely to usher in the greatest survival crisis. This will not only affect the music as a non-listed system, listed companies may not escape the music. This is largely related to Jia Yue Ting in the pledge of loans, often listed companies [url=http://www.nikeneo.com/mens-shoes-air-max-90-87-c-84_88_90.html]Air Max 90 87[/url] as a pledge of equity. According to the announcement on July 4 evening music Watch, Jay Yeting total frozen 519133322 shares, accounting for the proportion of music shares held by its 99.06%, accounting for the total share of music as the proportion of 26.03%. The current music Watch is still in the suspension stage, the suspension price of 30.68 yuan, the total market value of 61.2 billion, which means that the total value of Jaying Ting frozen equity close to 16 billion yuan. If this part of the equity eventually into the creditor side, the impact of music for the network will not only stay in public opinion so simple. An analyst to explain to Tencent technology, in general, [url=https://www.louboutinco.fr/]Christian Louboutin[/url] the equity was frozen in the short term will not have a direct impact on the listed companies, but the variable is Jay Yuting and creditors will sign what kind of supplementary agreement, once the two sides can not reach an agreement, do not rule out the shares Is forced to sell out the possibility of this time not only will affect the shares of non-listed companies, listed companies will also suffer the impact. 'Once the stock was sold in the secondary market, music Watch stock prices may also usher in a continuous drop, which will become the last straw down.' The person said. In the current music as the capital cycle, there are large value assets can not immediately become cash, which includes copyright, real estate and so on. This part of the value of assets on the one hand, as part of the collateral, on the other hand also propped up the music as the basic disk ----- with some shell companies, music as the market there are music video, music as the music, music, television and many Quality business, even look at the non-listed business, music as the film industry, music as sports and other business also continue to healthy development of space. A person in charge of [url=https://www.mkfeel.fr/]sac michael kors[/url] a wind control company listed to Tencent Technology said that the remaining basic disk determines the existence of music is still hope to resolve the crisis. 'The music company, especially the high-quality assets of the listed company system is still a lot, as long as the right track, [url=https://www.vbags.co.uk/]cheap celine bags[/url] repayment of the possibility of great.' The person stressed that the relevant creditors need to pay attention to this point, otherwise, The rush will only completely destroy its basic disk, and thus completely lose everything. But it is clear that the time to leave the music has been less and less, the organization's patience is declining. In the June [url=http://www.nikeneo.com/]Cheap Nike Shoes For Men[/url] 28 music at the annual shareholders meeting, Jia Yue Ting openly admitted that although the music received 9.7 billion in funds, the fact that more [url=http://www.nikeneo.com/size-14-15-16-c-212.html]Size 14 15 16 Mens Shoes[/url] than 150 billion yuan repayment, but still did not receive follow-up financial institutions, financial support, the majority or wait and see attitude. 'Sunny umbrella, rainy day umbrella,' the banking institutions will continue to Jia Yue Ting enough time, may determine [url=https://www.gooseca.co.uk/]canada goose outlet[/url] the [url=https://www.mkco.fr/]Michael Kors Sac[/url] final fate of music.﻿Americans are Chinese smart phone 'stunned': charge once [url=http://www.nikeneo.com/nike-air-max-womens-shoes-c-84_129.html]Discount Nike Womens Shoes[/url] a week July 4 reported that according to the United States, 'Forbes' magazine website on July 2 published entitled 'This is a Chinese mobile phone charge a full week with a' article, the author of the West. Article excerpts are as follows: If you are tracking any type of economic news, over the years you will continue to hear how important the Chinese market is. This is Hollywood, the US National Basketball Association, Apple, Facebook, and so can not wait to have a place where there is a place. But to really understand how big the Chinese market, see: almost only sold in China, Vivo (Vivo) and Oupo (Oppo) among the world's top five mobile phone manufacturers (according to sales rankings). And for Americans, brands like Oupo, little known, unknown (in the [url=https://www.coachx.fr/]Commande pas cher Coach Drawstring[/url] United States, LG / Sony / BlackBerry's popularity is its 5000 times). However, just bigger in China, is enough to make you in the global list on top, ahead of Sony, LG and BlackBerry. This shows why the countless Chinese mobile phone brand seems to launch new models every other week. Western and Asian people may have heard of Huawei and millet and a plus mobile phone is the favorite of each of the Western Andrews geeks, but heard of Vernee? Gionee Meizu (Meizu)? Googee? Small pepper (Xiaolajiao)? Blackview Leader (Leagoo)? Oukitel These are just a few of the dozens of less famous Chinese mobile phone brands in several. For them, they only need to trai
