### ISSUE TITLE
brpc latency时间收集不准确

### ISSUE THREAD

**Issue by Redfriday** [brpc/brpc#492]
目前观察到brpc timer使用cpu频率获取时间，而cpu频率是变化的，导致获取的延迟不准确，不知道是否确实有这个问题？

**Comment by gtarcoder** [comment]
我们测试发下，butil/time.h 中的 butil::Timer 的start 和 stop函数使用了 cpu_wide_time_ns， 这个函数会在启动的时候 获取一次 invariant_cpu_freq, 而真实的 cpu frequency会不断变化的。 且多核场景下，不同核心的 frequency也不同。 

`// ---------------------------------------------------------------
// Get cpu-wide (wall-) time.
// Cost ~9ns on Intel(R) Xeon(R) CPU E5620 @ 2.40GHz
// ---------------------------------------------------------------
// note: Inlining shortens time cost per-call for 15ns in a loop of many
//       calls to this function.
inline int64_t cpuwide_time_ns() {
    if (detail::invariant_cpu_freq > 0) {
        const uint64_t tsc = detail::clock_cycles();
        const uint64_t sec = tsc / detail::invariant_cpu_freq;
        // TODO: should be OK until CPU's frequency exceeds 16GHz.
        return (tsc - sec * detail::invariant_cpu_freq) * 1000000000L /
            detail::invariant_cpu_freq + sec * 1000000000L;
    } else if (!detail::invariant_cpu_freq) {
        // Lack of necessary features, return system-wide monotonic time instead.
        return monotonic_time_ns();
    } else {
        // Use a thread-unsafe method(OK to us) to initialize the freq
        // to save a "if" test comparing to using a local static variable
        detail::invariant_cpu_freq = detail::read_invariant_cpu_frequency();
        return cpuwide_time_ns();
    }
}
`
@jamesge  是不是有这个问题呢？ 以及，该怎么高效获取一个精确的时间呢？

**Comment by jamesge** [comment]
#414 这里有一些解释。按道理constant_tsc(the TSC runs at constant frequency irrespective of P/T- states)和nonstop_tsc(TSC does not stop in deep C-states)，说明tsc是可用作wall-time的。

**Comment by gethinzhang** [comment]
@jamesge 会不会是因为read_cpu_frequency在不同核读到的值不一样，但是代码里面只执行了一次 detail::read_invariant_cpu_frequency();这样后续的时间都会按照这个cpu frequency校准？

**Comment by gethinzhang** [comment]
@gtarcoder 的意思感觉应该是不同的核在cat /proc/cpuinfo的时候，得到的cpu MHz其实是不稳定的，而且不同的核差别可能大。而贴的那段代码是只会获取一次invariant_cpu_freq，这样可能会导致整个耗时都会收到第一次收集的那个核频率影响，导致后续的收集会有持续的偏移吧？

**Comment by jamesge** [comment]
@gethinzhang , constant_tsc的意思就是TSC的频率和cpu降频无关。能贴一下对应机器的cpuinfo么，也许是cpu有新的状态了。

**Comment by jamesge** [comment]
intel对于tsc完整的描述：

16.11.1 Invariant TSC

The time stamp counter in newer processors may support an enhancement, referred to as invariant TSC. Processor's support for invariant TSC is indicated by CPUID.80000007H:EDX[8]. (X86_FEATURE_CONSTANT_TSC + X86_FEATURE_NONSTOP_TSC)

The invariant TSC will run at a constant rate in all ACPI P-, C-. and T-states. This is the architectural behavior moving forward. On processors with invariant TSC support, the OS may use the TSC for wall clock timer services (instead of ACPI or HPET timers). TSC reads are much more efficient and do not incur the overhead associated with a ring transition or access to a platform resource.

**Comment by gtarcoder** [comment]
@jamesge  这是截取的其中的两个核的cpuinfo， flags 是有 constant_tsc 和 nonstop_tsc 的。
`

processor       : 30
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
stepping        : 1
microcode       : 0xb00002c
cpu MHz         : 1210.345
cache size      : 20480 KB
physical id     : 0
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 15
initial apicid  : 15
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bugs            :
bogomips        : 4199.85
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 31
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
stepping        : 1
microcode       : 0xb00002c
cpu MHz         : 1199.963
cache size      : 20480 KB
physical id     : 1
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 31
initial apicid  : 31
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bugs            :
bogomips        : 4201.11
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

`

不过我看代码实现 int64_t read_cpu_frequency(bool* invariant_tsc)  直接读取了第一个核的cpu 频率freq，然后用 tsc / freq 得到时间，怀疑这是不是 constant_tsc的正确做法呢？  
[这里](https://stackoverflow.com/questions/35123379/getting-tsc-rate-in-x86-kernel)是另外的获取方法：

`

The TSC rate is directly related to "cpu MHz" in /proc/cpuinfo. Actually, the better number to use is "bogomips". The reason is that while the freq for TSC is the max CPU freq, the current "cpu Mhz" can vary at time of your invocation.

The bogomips value is computed at boot. You'll need to adjust this value by number of cores and processor count (i.e. the number of hyperthreads) That gives you [fractional] MHz. That is what I use to do what you want to do.

To get the processor count, look for the last "processor: " line. The processor count is <value> + 1. Call it "cpu_count".

To get number of cores, any "cpu cores: " works. number of cores is <value>. Call it "core_count".

So, the formula is:

smt_count = cpu_count;
if (core_count)
    smt_count /= core_count;
cpu_freq_in_khz = (bogomips * scale_factor) / smt_count;

`

**Comment by gethinzhang** [comment]
@jamesge 戈兄，感觉这个问题现在不是rdstc问题，感觉是获取freq的方式有点问题

**Comment by gtarcoder** [comment]
https://github.com/brpc/brpc/pull/494 @jamesge  我想用这种方式 去获取 cpu frequency，你看下是否合适？

**Comment by gtarcoder** [comment]
可以确定brpc的timer 获取时间是不准确的（我们的服务已经出现多次计时不准的问题了）。 @jamesge  能给看下PR 不？

**Comment by gtarcoder** [comment]
@gydong  bvar监控服务的时延； 以及brpc 服务的好多用到timer的地方，只要用了 cpu_wide_time， 那么就不准确。一方面影响了很多依赖time的逻辑，比如redis 超时；另外也对我们对服务优化带来很大干扰。

**Comment by jamesge** [comment]
@gtarcoder 你觉得 #497 能解决你目前的问题么？如果方便的话请帮忙测试一下。你自己提的 #494 是基于bogomips的，和cpu型号关系密切，现在看起来也不是很合适的解决方法。

**Comment by gtarcoder** [comment]
@jamesge  我觉得这个是可以解决我们的问题。我觉得这个改动，只需要进行单测就可以。 我可以帮忙在我们机器上测试下。

btw，这种使用tsc的方法，对cpu型号依赖很大，做到通用性不容易。另外，我们自己用的时候，对brpc代码进行了稍微的修改，所有使用 tsc的地方，都使用 clock_getime。之前单独测试  tsc 和 clock_gettime，发现二者几乎没有性能上的差别。

**Comment by jamesge** [comment]
新版本glibc中确实能观察到gettimeofday和CLOCK_REALTIME/MONOTONIC的性能都不错，未来可以考虑brpc完全不使用rdtsc。
你也可以在自己机器上编译下test目录，并运行./test_butil --gtest_filter=BaiduTimeTest.*  运行结果可以在这里贴一下

**Comment by gtarcoder** [comment]
@jamesge   测试了  #497  的实现，在intel cpu的机器上，拿到的时钟是准确的。比较了 sleep 相同的时间的情况下， clock_gettime 和 cpu_wide_time 两种方式的计时，差别很小。
