### ISSUE TITLE
brpc的发布版本控制以及质量保证是怎么做的

### ISSUE THREAD

**Issue by imotai** [brpc/brpc#507]
这里不是批评，我们的系统已经深度使用brpc, 因为关心所以提出以下问题

第一个版本控制，目前brpc 应该没有做过多发布版本控制，都是走合并到master，会存在如下问题
* 问题回溯不方便，如果使用方没有记录commit id,就不知道真正使用的代码版本， 出了问题，brpc维护者也不知道该排查哪段代码

建议走发布版本，比如使用tag记录，并且brpc内部通过codegen方式把版本记录下来

第二个问题是质量保证，请问brpc在质量方面是怎么保证 Industrial-grade RPC framework？

**Comment by jamesge** [comment]
1. 之后会建立dev分支，定期合入master。brpc是为单根开发(mono-repo)设计的，我们希望用户依赖master版本，而不是某个tag。新版本虽然可能引入bug，但同时也会修复老问题，整体上利大于弊。
2. brpc本身有较多的测试，质量有基本的保障，另一方面brpc在百度内是主干发布，更新后会在
大量产品线中得到实际检验。目前最新数据是有200万个服务实例，所以很微小的bug也是会触发的。

每次提交我们会避免恶性的bug，但是由于rpc本身的复杂性以及和系统的耦合性，一些依赖被打破也是难以避免的，在公司内这可以通过单根开发和持续集成来及时发现，但开源社区只能通过用户反馈了。所以用户及时提issue对修正问题是很重要的。

具体到 #500，去掉动态修改的功能是by design，一方面是简化实现，另一方面是我们认为auto能够代替用户的设置。所以我还是建议你们先测试一下auto，然后再决定是否要自行设置。

**Comment by imotai** [comment]
![image](https://user-images.githubusercontent.com/8623385/46256628-d0861780-c4df-11e8-80fc-56e107bcac20.png)
@jamesge  又出问题了。。。 ，300多G内存在运行状态出现core dump了，与profile有关系么？

**Comment by jamesge** [comment]
看一下具体的coredump内容吧，也建议你们的服务跑一下gcc自带的address sanitizer

**Comment by imotai** [comment]
> 看一下具体的coredump内容吧，也建议你们的服务跑一下gcc自带的address sanitizer

core被截断了

**Comment by dl239** [comment]
<img width="1201" alt="wechatimg2744" src="https://user-images.githubusercontent.com/6183996/46295402-8ded3980-c5ca-11e8-9d02-9a51e72926ae.png">
@jamesge 复现出一个core来

**Comment by imotai** [comment]
> <img alt="wechatimg2744" width="1201" src="https://user-images.githubusercontent.com/6183996/46295402-8ded3980-c5ca-11e8-9d02-9a51e72926ae.png">
> 
> @jamesge 复现出一个core来

brpc这个core和 并发基数器给我们的客户带来的损失太大了，让我们不得不质疑brpc的质量问题，我已经复现一次问题了
![image](https://user-images.githubusercontent.com/8623385/46325248-00413680-c62a-11e8-8fc4-45e9956285fb.png)
但是这个不是core ，所以排查很困难，而且复现也是偶发的，所以麻烦@jamesge check一下代码

**Comment by imotai** [comment]
> 1. 个
单根开发(mono-repo) ，如果出现了bug, 但是也没有在修复列表中，都没法知道当时出问题的版本代码，怎么排查？而且 brpc能够保证新版本不影响老版本么，我反而觉得加tag只是对单根开发(mono-repo)一个很好的补充

**Comment by peiyuanzheng** [comment]
@imotai ，你们的程序有链接 tcmalloc_and_profiler.a 吗？
