### ISSUE TITLE
brpc max_connection_pool_size not work?

### ISSUE THREAD

**Issue by seiyap70** [brpc/brpc#89]
I set max_connection_pool_size but not work with "_options.connection_type = "pooled";_",  which makes create and close socket frequently. I look at the code at `inline int SocketPool::GetSocket(SocketUniquePtr* ptr) `,  the **connection_pool_size** used compare wit zero.

**Comment by jamesge** [comment]
max_connection_pool_size is a soft limit which does not prevent you from creating new connections. Instead, it takes effects when a socket is [returned to the pool](https://github.com/brpc/brpc/blob/3a2dee2845ec9c011b2cf8bb060590c5422e2d3b/src/brpc/socket.cpp#L2185). If the limit is reached, the socket is closed directly rather than being returned.

**Comment by seiyap70** [comment]
@jamesge oh, Thanks. I did not noticed  at there.
